//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieWandelPad.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilieWandelPad.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app was developed by Jelle Metzlar for Stichting Promotie Kaag. We hope you enjoy the route..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close navigation.
        /// </summary>
        public static string CloseNavigation {
            get {
                return ResourceManager.GetString("CloseNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not supported.
        /// </summary>
        public static string DeviceNotSupported {
            get {
                return ResourceManager.GetString("DeviceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For app related questions, feel free to email at:.
        /// </summary>
        public static string ForQuestions {
            get {
                return ResourceManager.GetString("ForQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have fun!.
        /// </summary>
        public static string HaveFun {
            get {
                return ResourceManager.GetString("HaveFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string IgnoreButton {
            get {
                return ResourceManager.GetString("IgnoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for GPS signal....
        /// </summary>
        public static string LookingForGPS {
            get {
                return ResourceManager.GetString("LookingForGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no long on route, if you receive this message after just starting, please press reset route, if you wish to skip part of the route press skip to my location, if you are taking a temporary stop and plan to go back, please press ignore. You can skip in the future by visiting the menu..
        /// </summary>
        public static string OffRouteText {
            get {
                return ResourceManager.GetString("OffRouteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your visit to Kaag. For more information about the surroundings:.
        /// </summary>
        public static string RouteFinishedText {
            get {
                return ResourceManager.GetString("RouteFinishedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset route.
        /// </summary>
        public static string RouteResetButton {
            get {
                return ResourceManager.GetString("RouteResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to my location.
        /// </summary>
        public static string RouteSkipButton {
            get {
                return ResourceManager.GetString("RouteSkipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit Kaag or Buitenkaag before starting navigation..
        /// </summary>
        public static string VisitKaag {
            get {
                return ResourceManager.GetString("VisitKaag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Kaag.nl.
        /// </summary>
        public static string VisitWebsite {
            get {
                return ResourceManager.GetString("VisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading the Kaag hiking navigation app! The short route you are about to walk, will take you along some of the most interesting places on the island. A couple of highlights along the route will trigger an information prompt on your device, keep an eye out!.
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Hiker!.
        /// </summary>
        public static string WelcomeHiker {
            get {
                return ResourceManager.GetString("WelcomeHiker", resourceCulture);
            }
        }
    }
}
