//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieWandelPad.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FamilieWandelPad.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DeviceNotSupported {
            get {
                return ResourceManager.GetString("DeviceNotSupported", resourceCulture);
            }
        }
        
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        public static string HaveFun {
            get {
                return ResourceManager.GetString("HaveFun", resourceCulture);
            }
        }
        
        public static string WelcomeHiker {
            get {
                return ResourceManager.GetString("WelcomeHiker", resourceCulture);
            }
        }
        
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        public static string LookingForGPS {
            get {
                return ResourceManager.GetString("LookingForGPS", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        public static string ForQuestions {
            get {
                return ResourceManager.GetString("ForQuestions", resourceCulture);
            }
        }
        
        public static string CloseNavigation {
            get {
                return ResourceManager.GetString("CloseNavigation", resourceCulture);
            }
        }
        
        public static string RouteFinishedText {
            get {
                return ResourceManager.GetString("RouteFinishedText", resourceCulture);
            }
        }
        
        public static string VisitWebsite {
            get {
                return ResourceManager.GetString("VisitWebsite", resourceCulture);
            }
        }
        
        public static string VisitKaag {
            get {
                return ResourceManager.GetString("VisitKaag", resourceCulture);
            }
        }
        
        public static string OffRouteText {
            get {
                return ResourceManager.GetString("OffRouteText", resourceCulture);
            }
        }
        
        public static string RouteResetButton {
            get {
                return ResourceManager.GetString("RouteResetButton", resourceCulture);
            }
        }
        
        public static string RouteSkipButton {
            get {
                return ResourceManager.GetString("RouteSkipButton", resourceCulture);
            }
        }
        
        public static string IgnoreButton {
            get {
                return ResourceManager.GetString("IgnoreButton", resourceCulture);
            }
        }
    }
}
